M48
; DRILL file {KiCad (6.0.5)} date Sat May 28 10:37:04 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-28T10:37:04-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X3.7628Y-3.3114
X3.7628Y-3.539
T2
X2.6965Y-2.9764
X2.6965Y-3.0945
T3
X2.4016Y-2.9134
X2.4016Y-3.9764
X3.8583Y-2.9134
X3.8583Y-3.9764
T0
M30
